# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano@2.0.0//zmk" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano@2.0.0//zmk
#     shield: reviung41
#
---
include:
    # Dongle builds
  - board: xiao_ble//zmk
    shield: urchin_dongle rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: xiao_dongle
  - board: nice_nano@2.0.0//zmk
    shield: urchin_dongle poor_mans_led
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: urchin_dongle

    # Split halves (peripherals when paired with dongle)
  - board: nice_nano@2.0.0//zmk
    shield: urchin_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: urchin_left_peripheral
  - board: nice_nano@2.0.0//zmk
    shield: urchin_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: urchin_left_central
  - board: nice_nano@2.0.0//zmk
    shield: urchin_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: urchin_right

    # Reset shields
  - board: nice_nano@2.0.0//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: settings_reset
