#include "../../../rgbled_adapter.conf"

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_SLEEP=n

# Enable zmk studio
CONFIG_ZMK_STUDIO=y

# Improve connection stability
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# Battery reporting from peripherals
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
